---
application:
  name: "nodejs-posgresql-deploy"
  project: "test"
  organization: "QoveryCommunity"
routers:
- name: "main-nodejs-posgresql-deploy"
  routes:
  - application_name: "nodejs-posgresql-deploy"
    paths:
    - "/*"
